// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package goprotoc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgValue) Reset()         { *m = MsgValue{} }
func (m *MsgValue) String() string { return proto.CompactTextString(m) }
func (*MsgValue) ProtoMessage()    {}
func (*MsgValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *MsgValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgValue.Unmarshal(m, b)
}
func (m *MsgValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgValue.Marshal(b, m, deterministic)
}
func (m *MsgValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgValue.Merge(m, src)
}
func (m *MsgValue) XXX_Size() int {
	return xxx_messageInfo_MsgValue.Size(m)
}
func (m *MsgValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgValue.DiscardUnknown(m)
}

var xxx_messageInfo_MsgValue proto.InternalMessageInfo

func (m *MsgValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MethodVal struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Reply                int32    `protobuf:"varint,4,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MethodVal) Reset()         { *m = MethodVal{} }
func (m *MethodVal) String() string { return proto.CompactTextString(m) }
func (*MethodVal) ProtoMessage()    {}
func (*MethodVal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *MethodVal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodVal.Unmarshal(m, b)
}
func (m *MethodVal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodVal.Marshal(b, m, deterministic)
}
func (m *MethodVal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodVal.Merge(m, src)
}
func (m *MethodVal) XXX_Size() int {
	return xxx_messageInfo_MethodVal.Size(m)
}
func (m *MethodVal) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodVal.DiscardUnknown(m)
}

var xxx_messageInfo_MethodVal proto.InternalMessageInfo

func (m *MethodVal) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *MethodVal) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MethodVal) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MethodVal) GetReply() int32 {
	if m != nil {
		return m.Reply
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgValue)(nil), "goprotoc.MsgValue")
	proto.RegisterType((*MethodVal)(nil), "goprotoc.MethodVal")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xcf, 0x07, 0x33, 0x92, 0x95, 0x14, 0xb8,
	0x38, 0x7c, 0x8b, 0xd3, 0xc3, 0x12, 0x73, 0x4a, 0x53, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x40, 0x0c,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x29, 0x94, 0x8b, 0xd3, 0x37, 0xb5, 0x24,
	0x23, 0x3f, 0x25, 0x2c, 0x31, 0x47, 0x48, 0x8c, 0x8b, 0x2d, 0x17, 0xcc, 0x81, 0xaa, 0x81, 0xf2,
	0x84, 0x78, 0xb8, 0x18, 0x2b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x18, 0x2b, 0x40, 0xbc,
	0x4a, 0x09, 0x66, 0x08, 0xaf, 0x12, 0x64, 0x6c, 0x51, 0x6a, 0x41, 0x4e, 0xa5, 0x04, 0x0b, 0x58,
	0x04, 0xc2, 0x49, 0x62, 0x03, 0x3b, 0xc0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x1b, 0xd1,
	0x10, 0x97, 0x00, 0x00, 0x00,
}
